=  Documentation brought to life: Asciidoctor & Gradle
Markus Schlichting <m.schlichting@mynethome.de>

== Presentation

Please find the presentation slides at https://github.com/madmas/AsciidoctorGradle-Doc2Life/raw/master/presentation/Slides_JavaForum2016.pdf[presentation/Slides_JavaForum2016.pdf]

== Examples

The examples are accessible via the branches within this repository:

|===
|branch name | description

|master
| first example, showing the basic gradle build generating HTML and PDF from `src/doc/main.adoc`, demonstrating AsciiDoctor syntaxt and base features

|includeByLine
| demonstrate including a code snippet via reference by line numbers

|includeByLabel
| demonstrate including a code snippet via reference by tag

|variables
| demonstrate passing the version number from the build into the generated document

|livingDoc
| demonstate using a CSV a source for data driven tests and the generated documentation at the same time

|===


== Resources

As the references links listed on the last slide do not work in the PDF:

http://danhyun.github.io/asciidoctor-gradle-examples/[asciidoctor-gradle-examples]

http://mojavelinux.github.io/decks/discover-zen-writing-asciidoc/cojugs201305/index.html[Discover the zen of writing AsciiDoc]

http://mojavelinux.github.io/decks/asciidoc-with-pleasure/[AsciiDoc with pleasure]

http://mgreau.com/slides/websocket-asciidoctor/DevNation2014/slides.html[When WebSockets meet AsciiDoctor]

http://www.slideshare.net/aalmiray/devoxx-asciidoctor-tips[Asciidoctor Tips from Devoxx]

http://mrhaki.blogspot.ch[MrHaki's Blog with regular posts on AsciiDoctor]

https://github.com/pledbrook/practical-groovy-public[Peter Ledbrook: 'Practical Groovy']

https://github.com/melix/gradlesummit2016-jigsaw-gradle/tree/master/slides[Slides with AsciiDoctor & Gradle by Cédric Champeau]
